# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac110424b6a67437c463ffc401a6a275ba8ff3d24550980232389f5bfed7208dd93d9e20f7aeed48bdad8aa4df36d67c0d9c244023c1004b3a7203d2c6a1d719

test:
  secret_key_base: 824fc42774a428cda352cf29d8df54ad0c79904f25e25e8581559d12ae34f9f95062b33be78ace7a9ca02b271191ffdcc3cda0a5e3f97ec28a1604447203b310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
